---
title: "Leslie Matrix Practice"
author: "Melannie Moreno Rolon"
format: html
editor: visual
---

# Matrices

```{r}
# Make a sequence of values from 1-10
my_values <- seq(from = 1, to = 10, by = 1)

# Look at it. Always
my_values
```

```{r}
# Convert into a matrix
my_matrix <- matrix(data = my_values, 
                    nrow = 2, 
                    ncol = 5, byrow = TRUE)
my_matrix
```

```{r}
#What happens if you don’t have enough elements in the matrix to contain your vector?
matrix(data = my_values, 
       nrow = 2,
       ncol = 3, byrow = TRUE)
```

```{r}
#What happens if your matrix has more elements than your vector?
matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

### **Scalar multiplication, addition and subtraction**

```{r}
#multiplication
4 * my_matrix
```

```{r}
#2X5 matrix
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = TRUE)
my_matrix2
```

### *Addition/Subtraction*

```{r}
my_matrix + my_matrix2 #add
my_matrix - my_matrix2 #subtract
```

```{r}
# Make a couple of 2x2 matrices ----
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

# Look at them ----
cats
dogs
```

### *Matrix Multiplication*

```{r}
# Matrix multiplication ----
cats %*% dogs
```

## Leslie Matrix Example

### ***Create the projection matrix:***

```{r}
#Create matrix
insect_leslie <- matrix(c(0,0,600,0.2,0,0,0,0.08,0),
                        nrow = 3, 
                        ncol = 3, byrow = TRUE)
insect_leslie
```

### ***Specify an initial condition***

```{r}
#insect lifestage poulation size (year 0)
insect_y0 <- c(1200, 700, 500)
```

### ***Find the populations for each life stage at t = 1 year***

```{r}
# Populations at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0

# Check it out ----
insect_y1 
```

```{r}
#Population for each life stage at year 2
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```

## **Another Leslie matrix example**

```{r}
# Create projection matrix
tree_leslie <- matrix(c(0,0,500,0.1,0,0,0,0.06,0.95),
                      nrow = 3,
                      ncol = 3, byrow = TRUE)
tree_leslie
```

```{r}
# Create initial conditions at year 0
tree_0 <- c(5000, 0, 0)

#values at year 1
tree_1 <- tree_leslie %*% tree_0
tree_1

#year 2
tree_2 <- tree_leslie %*% tree_1
tree_2

#year 3
tree_3 <- tree_leslie %*% tree_2
tree_3

#year 4
year_4 <- tree_leslie %*% tree_3
year_4
```
